### ISSUE TITLE
Possible Bugs with Lambda code and IAM policy

### ISSUE THREAD

**Issue by MK4G** [aws-samples/amazon-pinpoint-lex-bot#10]
Not a coder by trade so forgive me if the issues are basic misunderstandings. 

First an assumption I made. Line 23 of template.yaml has "YOURPINPOINTPROJECTID" and line 58 has "YOURPROJECTORAPPID". I assume these are the same thing, the AWS Pinpoint project ID. If not then what is what? The read me file says  that "PinpointApplicationId The ID of the Pinpoint project that you created earlier." so one of these should be the Pinpoint project ID. 

Next line 58 ends with "...endpoints/*" however when entered Lambda seems to think everything after the "/*" is a comment and grays it out. I tried putting everything starting with "arn:aws:" to the end of the line in double quotes but am not sure that is correct. It fixes the comment issue (all the code below that appears normal and not grayed out) but the code itself does not work. 

After adding the test code when testing the function I get many errors including "errorType": "Runtime.UserCodeSyntaxError" and the line below. Hopefully this helps debug the issue. 

undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.UserCodeSyntaxError","errorMessage":"SyntaxError: Unexpected identifier","stack":["Runtime.UserCodeSyntaxError: SyntaxError: Unexpected identifier","    at _loadUserApp (/var/runtime/UserFunction.js:98:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)","    at internal/main/run_main_module.js:17:47"]}

Also having issues is the IAM policy. When I copy in the policy and edit the region, account number, and Pinpoint ID I receive warnings every service.
* Pinpoint: specify apps resource ARN for the Sendmessage action, one or more actions may not support this resource. 
* Cloudwatch: Specify log-group resource ARN for the CreateLogGroup and 1 more action
* Cloudwatch: Specify log-stream resource ARN for the PutLogEvents action.
* Cloudwatch: One or more actions may not support this resource
* Lex V2: IAM does not recognize one or more actions. The action name might include a typo or might be part of a previewed or custom service. [issue with the PostContent permission, this does not exist?]
* Lex V2: One or more actions may not support this resource.
* Lex V2: IAM does not recognize one or more actions. The action name might include a typo or might be part of a previewed or custom service.
* Lex: One or more actions may not support this resource.

Are these warnings an issue, do you receive the same thing when this is tested on your end?

I realize this is a lot and hopefully most of the errors have one or two root causes. Any help you could provide would be welcome. Feel free to direct me to other resources. Note I found this by reading the post https://aws.amazon.com/blogs/messaging-and-targeting/create-an-sms-chatbox-with-amazon-pinpoint-and-lex/ and have followed the directions there, if there is another place I should be looking please let me know.

**Comment by ILAsoft** [comment]
Hi @MK4G,
I'll try to cover these in the order you listed:
1. Pinpoint uses Project and Application interchangeably, so yes, YOURPINPOINTPROJECTID=YOURPROJECTORAPPID=Pinpoint Project ID you used to do the initial setup.
2. The template file is not the Lambda/applicaion, the Lambda code is in the src sub-folder, while the template.yaml is in fact a Cloud Formation template - see Repository content section of the README. Please try going to Cloud Formation section of the console and uploading it through there _OR_ follow the steps in the README _OR_ follow the blog post. 
3. Warning are just that - they are warnings for you to consider, e.g. if you want to limit resources down to specific project vs all projects, etc.

**Comment by MK4G** [comment]
Thank you for the insight, I think I am nearly there. When I send a text message to my number the logs show the error "There is no alias named latest for the bot named...". I have created two aliases and tried both upper case and lower case letters in the name. In LexV2 there does not seem to be a way to "publish" the alias. Do you know why this might be happening? I think this is the last issue I need to overcome to have this start working.

**Comment by MK4G** [comment]
I still believe there is an issue with the code published but I have switched to using a Python solution so no longer need this resolved. Thanks for your help and good luck with the code. :)
